-- Create Periods table
CREATE TABLE IF NOT EXISTS periods (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date VARCHAR(255),
    end_date VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

-- Create Historical Events table
CREATE TABLE IF NOT EXISTS events (
    id INT PRIMARY KEY,
    period_id INT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    date VARCHAR(255),
    location VARCHAR(255),
    location_coordinates_lat DECIMAL(9,6),
    location_coordinates_lng DECIMAL(9,6),
    theme JSON,
    sources JSON,
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (period_id) REFERENCES periods(id)
);

-- Create Medias table
CREATE TABLE IF NOT EXISTS medias (
    id INT PRIMARY KEY,
    event_id INT,
    type ENUM('image', 'video') NOT NULL,
    url VARCHAR(255) NOT NULL,
    text TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (event_id) REFERENCES events(id)
);

-- Insert data into 'medias' table
-- Note: Single quotes in 'text' fields have been escaped (e.g., d' -> d'')
INSERT INTO medias (id, event_id, type, url, text, created_at, updated_at) VALUES
(1, 1, 'image', 'https://s.rfi.fr/media/display/ecfa78a6-b648-11ee-bc30-005056bf30b7/w:1280/p:4x3/Photo%20de%20Une%20Dessin%20site%20Shiyu.jpg', 'Crâne d''Homo sapiens de Jebel Irhoud', NOW(), NOW()),
(2, 1, 'video', 'https://www.youtube.com/watch?v=REPkDlRMQNs&pp=ygUXYXBwYXJpdGlvbiBob21vIHNhcGllbnPSBwkJhAkBhyohjO8%3D', 'Reconstitution de la vie des premiers Homo sapiens', NOW(), NOW()),
(3, 2, 'image', 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Lascaux_painting.jpg', 'Peintures rupestres de Lascaux', NOW(), NOW()),
(4, 2, 'video', 'https://youtu.be/0mkrUOZ_APg', 'Visite virtuelle de la grotte de Lascaux', NOW(), NOW()),
(5, 3, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/800px-Stonehenge2007_07_30.jpg', 'Stonehenge au lever du soleil', NOW(), NOW()),
(6, 3, 'video', 'https://www.youtube.com/watch?v=4FRnh8nHAwQ&pp=ygUaQ29uc3RydWN0aW9uIGRlIFN0b25laGVuZ2U%3D', 'Vidéo sur les théories de construction de Stonehenge', NOW(), NOW()),
(7, 4, 'image', 'https://hommenisciences.wordpress.com/wp-content/uploads/2021/11/feu-prehistoire-gary-todd-flickr-dp.jpg?w=799', 'Reconstitution d''un foyer préhistorique', NOW(), NOW()),
(8, 4, 'image', 'https://s1.qwant.com/thumbr/0x0/8/c/f9ea4dd8e37d037ad04b01660638b686f017fbe8b8b2d6a882addff2afdad1/campementhomohabilis.jpg?u=http%3A%2F%2Fimg.webme.com%2Fpic%2Fc%2Fcelinette%2Fcampementhomohabilis.jpg&q=0&b=1&p=0&a=1', 'Reconstitution d''un foyer préhistorique', NOW(), NOW()),
(9, 4, 'video', 'https://youtu.be/tH0Kt23_51M', 'Vidéo documentaire sur la maîtrise du feu', NOW(), NOW()),
(10, 5, 'image', 'https://www.science-et-vie.com/wp-content/uploads/scienceetvie/2016/02/aux-origines-agriculture.jpg', 'Scène agricole néolithique', NOW(), NOW()),
(11, 5, 'image', 'https://www.hominides.com/wp-content/uploads/2022/03/les-premiers-agriculteurs.jpg', 'Scène agricole néolithique', NOW(), NOW()),
(12, 6, 'image', 'https://www.aude-lauvergnas-ceramique.fr/wp-content/uploads/2010/05/c%C3%A9ramiques-n%C3%A9olithique-1.jpg', 'Poteries néolithiques anciennes', NOW(), NOW()),
(13, 6, 'image', 'https://reperio-deco.com/wp-content/uploads/2024/07/30570-1.webp', 'Origines de la poteries', NOW(), NOW()),
(14, 7, 'image', 'https://www.animo-petfood.com/img/cms/2021/domestication%20du%20chien/domestication-du-chien_1.jpg', 'Domestication du chien', NOW(), NOW()),
(15, 7, 'image', 'https://static.nationalgeographic.fr/files/styles/image_3200/public/2f74xwt.jpg?w=1900&h=1174', 'Domestication du chien', NOW(), NOW()),
(16, 8, 'image', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Prehistoric_Tools_-_Les_Combarelles_-_Les_Eyzies_de_Tayac_-_MNP.jpg', 'Outils lomekwiens ou oldowayens', NOW(), NOW()),
(17, 8, 'video', 'https://youtu.be/zFO16WrO-rY', 'Vidéo sur la fabrication d''outils préhistoriques', NOW(), NOW()),
(18, 9, 'image', 'https://static.nationalgeographic.fr/files/styles/image_3200/public/_NG223_GENETIC-6.webp?w=760&h=505', 'Carte des migrations humaines préhistoriques', NOW(), NOW()),
(19, 9, 'video', 'https://youtu.be/8WYmymKfGHo', 'Vidéo sur la théorie "Out of Africa"', NOW(), NOW()),
(20, 10, 'image', 'https://images.ladepeche.fr/api/v1/images/view/5c1baaf78fe56f25e75272b7/large/image.jpg', 'Impact d''astéroïde (représentation artistique)', NOW(), NOW()),
(21, 10, 'video', 'https://www.youtube.com/watch?v=1GyMcGxhVJI&pp=ygUaRGlzcGFyaXRpb24gZGVzIGRpbm9zYXVyZXM%3D', 'Vidéo sur l''extinction des dinosaures', NOW(), NOW()),
(22, 11, 'image', 'https://museum.var.fr/ws/home/app/file/forcedownload/0190-okSE---2008-Photo-S.-Plailly---Reconstruction--Elisabeth-Daynes-Paris.jpg?key=38a9b4zo0k7rvzrt5zs25hp00key3t4fa&thumbw=1180&thumbh=400', 'Reconstitution d''un Néandertalien', NOW(), NOW()),
(23, 11, 'image', 'https://www.lejournaldesarts.fr/sites/lejournaldesarts/files/2018-07/neanderthaler-rekonstruktio.jpg', 'Reconstitution d''un Néandertalien', NOW(), NOW()),
(24, 11, 'image', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Homo_sapiens_neanderthalensis.jpg', 'Reconstitution d''un Néandertalien', NOW(), NOW()),
(25, 11, 'video', 'https://www.youtube.com/watch?v=lBLFicyWtE4&pp=ygUWTCdIb21tZSBkZSBOw6lhbmRlcnRhbA%3D%3D', 'Vidéo sur la vie et la disparition des Néandertaliens', NOW(), NOW()),
(26, 12, 'image', 'https://cdn.futura-sciences.com/sources/images/diaporama/chauvet/1110-chauvet.jpg', 'Peintures de la Grotte Chauvet', NOW(), NOW()),
(27, 12, 'image', 'https://cdn.futura-sciences.com/cdn-cgi/image/width=1024,quality=60,format=auto/sources/images/diaporama/chauvet/Fig.1.Chevaux.JPG', 'Image sur la Grotte Chauvet', NOW(), NOW()),
(28, 13, 'image', 'https://www.hominides.com/wp-content/uploads/2021/10/homme-de-chancelade.jpg', 'Sépulture de Qafzeh', NOW(), NOW()),
(29, 13, 'image', 'https://www.hominides.com/wp-content/uploads/2022/06/reconstitution-sepulture-chapelle-aux-saints-1024x710.jpg', 'Image sur la Chapelle aux Saints', NOW(), NOW()),
(30, 13, 'image', 'https://www.hominides.com/wp-content/uploads/2022/06/sepulture-noyen-sur-seine.jpg', 'Image sur la sépulture de Noyen-sur-Seine', NOW(), NOW()),
(31, 14, 'image', 'https://dailyscience.be/NEW/wp-content/uploads/2023/07/Outils-du-site-de-Chagyrskaya-Retouchoir-A-Outil-a-extremite-emoussee-B-Outil-a-extremite-biseautee-C-Outil-retouche-D-Copyirght-M.-.jpg', 'Outils en os préhistoriques (aiguilles, harpons)', NOW(), NOW()),
(32, 14, 'image', 'https://dailyscience.be/NEW/wp-content/uploads/2023/07/Comparaison-doutils-biseautes-fabriques-par-Neandertal-A-et-fabriques-par-Homo-Sapiens-B-%C2%A9-M.-Baumann-recoupe.jpg', 'Outils en os préhistoriques (aiguilles, harpons)', NOW(), NOW()),
(33, 15, 'image', 'https://img.over-blog-kiwi.com/0/42/78/76/20180917/ob_6836d0_9cafa8a83dae54c1799b53c1142025.png', 'Reconstitution de vêtements préhistoriques', NOW(), NOW()),
(34, 15, 'image', 'https://ce2barbalete.wordpress.com/wp-content/uploads/2020/04/habits-de-la-prc3a9histoire-2.png?w=1024', 'Reconstitution de vêtements préhistoriques', NOW(), NOW()),
(35, 16, 'image', 'https://www.hominides.com/wp-content/uploads/2022/05/reconstitution-habitat-neandertal-gontsy-1024x715.jpg', 'Reconstitution de hutte de Mezhirich (Ukraine)', NOW(), NOW()),
(36, 16, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/%E4%B8%89%E5%86%85%E4%B8%B8%E5%B1%B1%E9%81%BA%E8%B7%A1%E5%BE%A9%E5%85%83%E8%8C%85%E8%91%BA%E4%BD%8F%E5%B1%85.JPG/1200px-%E4%B8%89%E5%86%85%E4%B8%B8%E5%B1%B1%E9%81%BA%E8%B7%A1%E5%BE%A9%E5%85%83%E8%8C%85%E8%91%BA%E4%BD%8F%E5%B1%85.JPG', 'Reconstitution de hutte de Mezhirich (Ukraine)', NOW(), NOW()),
(37, 17, 'image', 'https://frise-chronologique.inrap.fr/sites/default/files/2021-07/2_-_paleolithique_moyen_-_innovations_majeures_-_version_finale_0.jpg', 'Carte montrant la diffusion de l''obsidienne', NOW(), NOW()),
(38, 18, 'image', 'https://www.laquintejuste.com/rde-data-bundle/201709/image/20170925-18-25-57-instrumentsprehistoriques_i01.jpg', 'Flûte préhistorique en os', NOW(), NOW()),
(39, 18, 'image', 'https://classic-intro.net/brevehistoire/Origines%20de%20la%20musique_fichiers/image003.jpg', 'Image des instruments préhistoriques', NOW(), NOW()),
(40, 18, 'video', 'https://youtu.be/bqgFK3kowgM', 'Vidéo/Audio de reconstitution sonore d''instruments préhistoriques', NOW(), NOW()),
(41, 19, 'image', 'https://i.ytimg.com/vi/IXRFMRspfhc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCb3J95JP70y0wzMZu0KDaYZ94LvQ', '', NOW(), NOW()),
(42, 19, 'video', 'https://youtu.be/IXRFMRspfhc', 'Vidéo/Audio de reconstitution sonore d''instruments préhistoriques', NOW(), NOW()),
(43, 20, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Weichsel-W%C3%BCrm-Glaciation.png/500px-Weichsel-W%C3%BCrm-Glaciation.png', 'Carte de l''extension des glaces au dernier maximum glaciaire', NOW(), NOW()),
(44, 20, 'video', 'https://www.youtube.com/watch?v=2mS73tyMwUc&pp=ygUmRmluIGRlIGxhIGRlcm5pw6hyZSBww6lyaW9kZSBnbGFjaWFpcmU%3D', 'Vidéo sur les conséquences de la fin de l''ère glaciaire', NOW(), NOW()),
(45, 21, 'image', 'https://historyweb.fr/wp-content/uploads/2014/06/charlemagne-site-histoire-historyweb-e1500728414133.jpg', 'Peinture du couronnement de Charlemagne', NOW(), NOW()),
(46, 21, 'video', 'placeholder:Vidéo sur l''importance du couronnement de Charlemagne', 'Vidéo sur l''importance du couronnement de Charlemagne', NOW(), NOW()),
(47, 22, 'image', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Bayeux_Tapestry_scene57_Harold_death.jpg', 'Scène de la Tapisserie de Bayeux montrant la bataille', NOW(), NOW()),
(48, 22, 'video', 'placeholder:Vidéo documentaire sur la Bataille de Hastings', 'Vidéo documentaire sur la Bataille de Hastings', NOW(), NOW()),
(49, 23, 'image', 'https://cms.alloprof.qc.ca/sites/default/files/styles/1200w/public/2020-07/h1437i7.jpg?itok=5PHquO4U', 'Chevaliers croisés (enluminure)', NOW(), NOW()),
(50, 23, 'video', 'placeholder:Vidéo documentaire sur l''histoire des Croisades', 'Vidéo documentaire sur l''histoire des Croisades', NOW(), NOW()),
(51, 24, 'image', 'https://cdn.essentiels.bnf.fr/media/images/cache/crop_doublelandscape_1000_500/rc/QmgNeuG9/uploads/media/image/20201204204949000000_pas_2673.jpg', NULL, NOW(), NOW()),
(52, 24, 'video', 'placeholder:Vidéo sur les techniques de construction des cathédrales gothiques', 'Vidéo sur les techniques de construction des cathédrales gothiques', NOW(), NOW()),
(53, 25, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Doutielt3.jpg/800px-Doutielt3.jpg', 'Enterrement de victimes de la peste noire à Tournai, dans les Annales de Gilles Le Muisit (1272-1352)', NOW(), NOW()),
(54, 25, 'image', 'https://static.nationalgeographic.fr/files/styles/image_3200/public/black-death-opener.webp?w=767&h=432', 'Ce tableau de 1562, « Le triomphe de la mort », de Pieter Bruegel l''Ancien, illustre la profonde impression laissée dans l''imaginaire européen par les épidémies et les guerres qui ont ravagé la société.', NOW(), NOW()),
(55, 25, 'video', 'placeholder:Vidéo documentaire sur la Peste Noire et ses conséquences', 'Vidéo documentaire sur la Peste Noire et ses conséquences', NOW(), NOW()),
(56, 26, 'image', 'https://www.larousse.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Bataille de Crécy ou d''Azincourt (enluminure)', NOW(), NOW()),
(57, 26, 'video', 'placeholder:Vidéo résumant la Guerre de Cent Ans', 'Vidéo résumant la Guerre de Cent Ans', NOW(), NOW()),
(58, 27, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Joan_of_Arc_miniature_graded.jpg/1200px-Joan_of_Arc_miniature_graded.jpg', 'Statue ou peinture de Jeanne d''Arc', NOW(), NOW()),
(59, 27, 'video', 'placeholder:Vidéo sur l''épopée de Jeanne d''Arc', 'Vidéo sur l''épopée de Jeanne d''Arc', NOW(), NOW()),
(60, 28, 'image', 'https://i.ytimg.com/vi/2OsIvR30zOQ/sddefault.jpg?sqp=-oaymwEmCIAFEOAD8quKqQMa8AEB-AH-BIAC4AOKAgwIABABGGUgTSg_MA8%3D&rs=AOn4CLCiXGAYgFEwPemEnmD0w1eHYaabbQ', 'Presse de Gutenberg (reconstitution)', NOW(), NOW()),
(61, 28, 'video', 'placeholder:Vidéo expliquant le fonctionnement de l''imprimerie de Gutenberg', 'Vidéo expliquant le fonctionnement de l''imprimerie de Gutenberg', NOW(), NOW()),
(62, 29, 'image', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Benjamin-Constant-The_Entry_of_Mahomet_II_into_Constantinople-1876.jpg', 'Peinture de la prise de Constantinople', NOW(), NOW()),
(63, 29, 'video', 'placeholder:Vidéo documentaire sur le siège et la chute de Constantinople', 'Vidéo documentaire sur le siège et la chute de Constantinople', NOW(), NOW()),
(64, 30, 'image', 'https://static1.colliderimages.com/wordpress/wp-content/uploads/2023/08/the-10-best-vikings-in-movies-and-tv-ranked.jpg', 'Drakkar viking', NOW(), NOW()),
(65, 30, 'video', 'placeholder:Vidéo documentaire sur l''histoire des Vikings', 'Vidéo documentaire sur l''histoire des Vikings', NOW(), NOW()),
(66, 31, 'image', 'https://wikirouge.net/w/images/a/ac/F%C3%A9odalisme.png', 'Schéma de la pyramide féodale', NOW(), NOW()),
(67, 31, 'video', 'placeholder:Vidéo expliquant le système féodal', 'Vidéo expliquant le système féodal', NOW(), NOW()),
(68, 32, 'image', 'https://www.larousse.fr/encyclopedie/data/images/1002964-Poitiers_l%C3%A9glise_Notre-Dame-la-Grande.jpg', 'Abbaye de Cluny', NOW(), NOW()),
(69, 32, 'video', 'placeholder:Vidéo présentant les caractéristiques de l''art roman', 'Vidéo présentant les caractéristiques de l''art roman', NOW(), NOW()),
(70, 33, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Joaquin_Pinto_-_The_Inquisition.JPG/220px-Joaquin_Pinto_-_The_Inquisition.JPG', 'Scène d''interrogatoire par l''Inquisition (gravure)', NOW(), NOW()),
(71, 33, 'video', 'placeholder:Vidéo expliquant le rôle et le fonctionnement de l''Inquisition médiévale', 'Vidéo expliquant le rôle et le fonctionnement de l''Inquisition médiévale', NOW(), NOW()),
(72, 34, 'image', 'https://cdn.futura-sciences.com/cdn-cgi/image/width=1024,quality=60,format=auto/sources/images/R%C3%A9union%20des%20docteurs%20de%20luniversit%C3%A9%20de%20Paris%20BnF.jpg', 'Leçon dans une université médiévale (enluminure)', NOW(), NOW()),
(73, 34, 'video', 'placeholder:Vidéo sur la naissance des universités au Moyen Âge', 'Vidéo sur la naissance des universités au Moyen Âge', NOW(), NOW()),
(74, 35, 'image', 'https://upload.wikimedia.org/wikipedia/commons/9/96/San_Gimignano_%281%29.jpg', 'Sceau d''une ville médiévale', NOW(), NOW()),
(75, 35, 'video', 'placeholder:Vidéo sur le mouvement communal au Moyen Âge', 'Vidéo sur le mouvement communal au Moyen Âge', NOW(), NOW()),
(76, 36, 'image', 'https://sup.sorbonne-universite.fr/sites/default/files/images/product/99.jpg', 'Alchimiste dans son laboratoire (gravure)', NOW(), NOW()),
(77, 36, 'video', 'placeholder:Vidéo sur l''histoire de l''alchimie', 'Vidéo sur l''histoire de l''alchimie', NOW(), NOW()),
(78, 37, 'image', 'https://i.ytimg.com/vi/5yCMSTaereg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBFRN7qm8ZUFH4a37mR1VYThC9HYg', 'Enseigne de guilde médiévale', NOW(), NOW()),
(79, 37, 'video', 'placeholder:Vidéo sur le rôle des corporations de métiers au Moyen Âge', 'Vidéo sur le rôle des corporations de métiers au Moyen Âge', NOW(), NOW()),
(80, 38, 'image', 'https://www.musique-medievale.fr/wp-content/uploads/2023/06/Comment-retrouver-un-morceau-de-musique-medievale.jpg', 'Partition de chant grégorien ou d''une enluminure avec musiciens', NOW(), NOW()),
(81, 38, 'video', 'placeholder:Vidéo/Audio d''extraits de musique médiévale (grégorien, polyphonie, troubadours)', 'Vidéo/Audio d''extraits de musique médiévale (grégorien, polyphonie, troubadours)', NOW(), NOW()),
(82, 39, 'image', 'https://cdn.essentiels.bnf.fr/media/images/cache/crop/rc/VRFPXUnn/uploads/media/image/20201204203556000000_pas_2309.jpg', 'Krak des Chevaliers ou du Château de Pierrefonds', NOW(), NOW()),
(83, 39, 'video', 'placeholder:Vidéo sur l''évolution et la construction des châteaux forts', 'Vidéo sur l''évolution et la construction des châteaux forts', NOW(), NOW()),
(84, 40, 'image', 'https://www.dunod.com/sites/default/files/styles/full/public/thumbnails/image/9782200617400-001-X.jpeg', 'Abbaye de Fontenay (Cistercien) ou d''un moine copiste', NOW(), NOW()),
(85, 40, 'video', 'placeholder:Vidéo sur le rôle des monastères au Moyen Âge', 'Vidéo sur le rôle des monastères au Moyen Âge', NOW(), NOW()),
(86, 41, 'image', 'https://www.interforum.fr/images/DEC/P3/9782707183422.jpg', 'Débarquement de Colomb (peinture)', NOW(), NOW()),
(87, 41, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les voyages de Christophe Colomb et leurs conséquences', NOW(), NOW()),
(88, 42, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg/640px-Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg', 'Portrait de Martin Luther', NOW(), NOW()),
(89, 42, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les débuts de la Réforme protestante', NOW(), NOW()),
(90, 43, 'image', 'https://panoramadelart.com/sites/default/files/filesPanorama/joconde_1.jpg', 'La Naissance de Vénus de Botticelli ou L''École d''Athènes de Raphaël', NOW(), NOW()),
(91, 43, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les grands artistes de la Renaissance italienne', NOW(), NOW()),
(92, 44, 'image', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Council_of_Trent.JPG', 'Peinture représentant une session du Concile de Trente', NOW(), NOW()),
(93, 44, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les décisions et l''impact du Concile de Trente', NOW(), NOW()),
(94, 45, 'image', 'https://upload.wikimedia.org/wikipedia/commons/5/52/Francois_Dubois_001.jpg', 'Massacre de la Saint-Barthélemy (peinture)', NOW(), NOW()),
(95, 45, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo résumant les Guerres de Religion en France', NOW(), NOW()),
(96, 46, 'image', 'https://upload.wikimedia.org/wikipedia/commons/2/25/%C3%89dit_de_Nantes._Page_24_-_Archives_Nationales_-_AE-II-763.jpg', 'Texte de l''Édit de Nantes (fac-similé)', NOW(), NOW()),
(97, 46, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant le contenu et la portée de l''Édit de Nantes', NOW(), NOW()),
(98, 47, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Ihs-logo.svg/1200px-Ihs-logo.svg.png', 'Portrait d''Ignace de Loyola', NOW(), NOW()),
(99, 47, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''histoire et l''influence des Jésuites', NOW(), NOW()),
(100, 48, 'image', 'https://ecoledephilosophie.org/IMG/jpg/1215522-systeme-de-copernic-cellarius.jpg', 'Schéma du système héliocentrique de Copernic', NOW(), NOW()),
(101, 48, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant la révolution copernicienne', NOW(), NOW()),
(102, 49, 'image', 'https://www.espace-sciences.org/sites/espace-sciences.org/files/documents/blogs/oceanographie/espace-sciences-rennes-blog-oceanographie-caravelles.jpg', 'Caravelle portugaise ou carte des voyages de Magellan', NOW(), NOW()),
(103, 49, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les grandes découvertes maritimes', NOW(), NOW()),
(104, 50, 'image', 'https://leonardointeractivemuseum.com/wp-content/uploads/2021/11/Leonardo-Interactive-Museum%C2%AE-autoritratto-di-Leonardo-da-Vinci-1024x1024.webp', 'La Joconde ou de l''Homme de Vitruve', NOW(), NOW()),
(105, 50, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur la vie et l''œuvre de Léonard de Vinci', NOW(), NOW()),
(106, 51, 'image', 'http://galeriemontblanc.com/cdn/shop/products/MichelAnge-LaCreationd_Adam.png?v=1630725341', 'David de Michel-Ange ou d''une fresque de la Chapelle Sixtine', NOW(), NOW()),
(107, 51, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les chefs-d''œuvre de Michel-Ange', NOW(), NOW()),
(108, 52, 'image', 'https://cdn-test.poetryfoundation.org/cdn-cgi/image/w=2292,h=1528,q=80/content/images/653f5eeafab7a9895af1eca68e97459c831812c6.jpeg', 'Portrait Chandos (supposé de Shakespeare)', NOW(), NOW()),
(109, 52, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''importance de Shakespeare dans la littérature', NOW(), NOW()),
(110, 53, 'image', 'https://www.larousse.fr/encyclopedie/data/images/1312889-Galil%C3%A9e.jpg', 'Portrait de Galilée ou de ses dessins de la Lune', NOW(), NOW()),
(111, 53, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les découvertes de Galilée et son procès', NOW(), NOW()),
(112, 54, 'image', 'https://www.laculturegenerale.com/wp-content/uploads/2016/12/contre-reforme-massacre-saint-barthelemy.jpg.webp', 'Massacre de Saint-Barthélemy', NOW(), NOW()),
(113, 54, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les aspects de la Contre-Réforme', NOW(), NOW()),
(114, 55, 'image', 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Angel_Appearing_to_Zacharias_%28detail%29_-_1486-90.JPG', 'Portrait d''Érasme par Holbein', NOW(), NOW()),
(115, 55, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les idées clés de l''humanisme de la Renaissance', NOW(), NOW()),
(116, 56, 'image', 'https://ehne.fr/sites/default/files/styles/image_notice/public/illustration/salvadori_fig_1.jpg?itok=Yl5Wo732', 'Planisphère de Mercator ou d''un portulan', NOW(), NOW()),
(117, 56, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''évolution de la cartographie à la Renaissance', NOW(), NOW()),
(118, 57, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/The_Concert_A22894.jpg/1200px-The_Concert_A22894.jpg', 'Partition de Palestrina ou d''un groupe de musiciens de la Renaissance', NOW(), NOW()),
(119, 57, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo/Audio d''exemples de musique de la Renaissance (polyphonie vocale, musique instrumentale)', NOW(), NOW()),
(120, 58, 'image', 'https://associationedit.fr/wp-content/uploads/2020/01/Image17.png', 'Portraits d''Élisabeth Ire ou d''Henri VIII montrant la mode de l''époque', NOW(), NOW()),
(121, 58, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''histoire de la mode à la Renaissance', NOW(), NOW()),
(122, 59, 'image', 'https://www.worldhistory.org/img/r/p/500x600/12362.png?v=1705846807', 'Reconstitution du Théâtre du Globe', NOW(), NOW()),
(123, 59, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur le théâtre à l''époque de Shakespeare', NOW(), NOW()),
(124, 60, 'image', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Helst%2C_Peace_of_M%C3%BCnster.jpg', 'Peinture de la signature du traité de Münster', NOW(), NOW()),
(125, 60, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les traités de Westphalie et leur importance', NOW(), NOW()),
(126, 61, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Salon_de_Madame_Geoffrin.jpg/220px-Salon_de_Madame_Geoffrin.jpg', 'Portrait de Voltaire ou d''une page de l''Encyclopédie', NOW(), NOW()),
(127, 61, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les idées des Lumières', NOW(), NOW()),
(128, 62, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Declaration_of_Independence_%281819%29%2C_by_John_Trumbull.jpg/330px-Declaration_of_Independence_%281819%29%2C_by_John_Trumbull.jpg', 'Peinture de la signature de la Déclaration d''indépendance', NOW(), NOW()),
(129, 62, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo résumant la Révolution américaine', NOW(), NOW()),
(130, 63, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Anonymous_-_Prise_de_la_Bastille.jpg/1200px-Anonymous_-_Prise_de_la_Bastille.jpg', 'La Prise de la Bastille ou La Liberté guidant le peuple', NOW(), NOW()),
(131, 63, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les grandes étapes de la Révolution française', NOW(), NOW()),
(132, 64, 'image', 'https://upload.wikimedia.org/wikipedia/commons/5/50/France_September_1812_prussia_occupied.jpg', 'La Prise de la Bastille ou La Liberté guidant le peuple', NOW(), NOW()),
(133, 64, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les grandes étapes de la Révolution française', NOW(), NOW()),
(134, 65, 'image', 'https://www.larousse.fr/encyclopedie/data/images/1315891-Congr%C3%A8s_de_Vienne.jpg', 'Peinture représentant les diplomates au Congrès de Vienne', NOW(), NOW()),
(135, 65, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les décisions et les conséquences du Congrès de Vienne', NOW(), NOW()),
(136, 66, 'image', 'https://www.researchgate.net/publication/337446469/figure/fig5/AS:828084064362496@1574442034078/Les-quatre-revolutions-industrielles.png', 'Machine à vapeur ou d''une usine du XIXe siècle', NOW(), NOW()),
(137, 66, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les causes et les conséquences des révolutions industrielles', NOW(), NOW()),
(138, 67, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Italia_1796-fr.svg/1200px-Italia_1796-fr.svg.png', 'Carte de l''Italie en 1796', NOW(), NOW()),
(139, 67, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les étapes de l''unification italienne', NOW(), NOW()),
(140, 68, 'image', 'https://upload.wikimedia.org/wikipedia/commons/9/95/American_Civil_War_Montage_2.jpg', 'Bataille de Gettysburg ou de soldats de la Guerre de Sécession', NOW(), NOW()),
(141, 68, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les causes et le déroulement de la Guerre de Sécession', NOW(), NOW()),
(142, 69, 'image', 'https://www.axl.cefan.ulaval.ca/afrique/images/afrique-coloniale-map.gif', 'Carte du partage de l''Afrique entre les puissances européennes', NOW(), NOW()),
(143, 69, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant la Conférence de Berlin et la colonisation de l''Afrique', NOW(), NOW()),
(144, 70, 'image', 'https://www.archives18.fr/image/1788667/236800?size=!2000,2000&region=full&format=jpg&crop=centre&realWidth=853&realHeight=600', 'Plan d''un navire négrier (Brookes)', NOW(), NOW()),
(145, 70, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur la traite négrière transatlantique', NOW(), NOW()),
(146, 71, 'image', 'https://haitiwonderland.com/assets/images/upload/blog/haiti-1er-janvier-en-haiti--celebration-de-l-independance-1718669376.jpg', 'Portrait de Toussaint Louverture ou de Jean-Jacques Dessalines', NOW(), NOW()),
(147, 71, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''histoire de la Révolution haïtienne', NOW(), NOW()),
(148, 72, 'image', 'https://upload.wikimedia.org/wikipedia/commons/2/21/Biard_Abolition_de_l%27esclavage_1849.jpg', 'Médaille abolitionniste "Am I Not a Man and a Brother?"', NOW(), NOW()),
(149, 72, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''histoire du mouvement abolitionniste', NOW(), NOW()),
(150, 73, 'image', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Kane_Prairie.jpg', 'Convoi de pionniers ou de la Ruée vers l''or en Californie', NOW(), NOW()),
(151, 73, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur la Conquête de l''Ouest', NOW(), NOW()),
(152, 74, 'image', 'https://i.ytimg.com/vi/H5TZvrNn2zw/sddefault.jpg', 'Paysage industriel du XIXe siècle (ex: bassin minier)', NOW(), NOW()),
(153, 74, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''industrialisation de l''Europe au XIXe siècle', NOW(), NOW()),
(154, 75, 'image', 'https://wikirouge.net/w/images/6/69/Nationalisme.png', 'Germania (allégorie de l''Allemagne) ou autre symbole nationaliste', NOW(), NOW()),
(155, 75, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant la montée du nationalisme au XIXe siècle', NOW(), NOW()),
(156, 76, 'image', 'https://www.contretemps.eu/wp-content/uploads/Difference-Between-Imperialism-and-Colonialism-1-e1610825093113.jpg', 'Caricature sur le partage du monde par les puissances impérialistes', NOW(), NOW()),
(157, 76, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les causes et les formes du nouvel impérialisme', NOW(), NOW()),
(158, 77, 'image', 'https://cms.alloprof.qc.ca/sites/default/files/styles/1200w/public/2020-07/la%20violence_0.jpg?itok=j_gVzlZ8', 'Grève ouvrière ou manifestation du 1er mai au XIXe siècle', NOW(), NOW()),
(159, 77, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''histoire du mouvement ouvrier', NOW(), NOW()),
(160, 78, 'image', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Annie_Kenney_and_Christabel_Pankhurst_%28cropped%29.jpg', 'Suffragettes manifestant ou d''Emmeline Pankhurst', NOW(), NOW()),
(161, 78, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur le combat des suffragettes pour le droit de vote', NOW(), NOW()),
(162, 79, 'image', 'https://www.hgsempai.fr/carto/wp-content/uploads/2024/02/1ere_mondialisation.png', 'Port de Londres ou de New York à la fin du XIXe siècle', NOW(), NOW()),
(163, 79, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant la première mondialisation', NOW(), NOW()),
(164, 80, 'image', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Montage_photo_premi%C3%A8re_guerre_mondiale.png/800px-Montage_photo_premi%C3%A8re_guerre_mondiale.png', 'Soldats dans les tranchées', NOW(), NOW()),
(165, 80, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les causes et le déroulement de la Première Guerre mondiale', NOW(), NOW()),
(166, 81, 'image', 'https://histoire-image.org/sites/default/files/2022-06/orpen-traite-versailles-signature.jpg', 'Signature du Traité de Versailles', NOW(), NOW()),
(167, 81, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo analysant les clauses et les conséquences du Traité de Versailles', NOW(), NOW()),
(168, 82, 'image', 'https://www.larousse.fr/encyclopedie/data/images/1313119-L%C3%A9nine_affiche.jpg', 'Lénine s''adressant à la foule', NOW(), NOW()),
(169, 82, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les événements de la Révolution russe', NOW(), NOW()),
(170, 83, 'image', 'https://m.media-amazon.com/images/I/71io7b2rlgL._AC_UF1000,1000_QL80_.jpg', 'Débarquement en Normandie ou de la Bataille de Stalingrad', NOW(), NOW()),
(171, 83, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire couvrant la Seconde Guerre mondiale', NOW(), NOW()),
(172, 84, 'image', 'https://www.icrc.org/sites/default/files/styles/desktop_full/public/document/image/genocide-home-150428.jpg.webp?itok=HRZQr9y_', 'Entrée d''Auschwitz-Birkenau ("Arbeit macht frei")', NOW(), NOW()),
(173, 84, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur l''histoire de la Shoah', NOW(), NOW()),
(174, 85, 'image', 'https://ehne.fr/sites/default/files/styles/image_notice/public/illustrations-documentaires/champi.jpg?itok=8EruKy10', 'Champignon atomique au-dessus d''Hiroshima ou Nagasaki', NOW(), NOW()),
(175, 85, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les bombardements atomiques et leurs conséquences', NOW(), NOW()),
(176, 86, 'image', 'https://www.telos-eu.com/medias/articles/coldwar.jpeg', 'Mur de Berlin ou de la Crise des missiles de Cuba', NOW(), NOW()),
(177, 86, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire expliquant les enjeux et les étapes de la Guerre froide', NOW(), NOW()),
(178, 87, 'image', 'https://i.ytimg.com/vi/X6k98xiamJ4/sddefault.jpg', 'Berlinois sur le Mur de Berlin le 9 novembre 1989', NOW(), NOW()),
(179, 87, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo d''archives de la chute du Mur de Berlin', NOW(), NOW()),
(180, 88, 'image', 'https://upload.wikimedia.org/wikipedia/commons/6/65/September_11_Photo_Montage.jpg', 'Tours jumelles en feu ou du site après l''effondrement', NOW(), NOW()),
(181, 88, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur les événements du 11 septembre', NOW(), NOW()),
(182, 89, 'image', 'https://www.who.int/images/default-source/wpro/coronavirus-2.jpg?sfvrsn=f3ceff40_19', 'Personnel soignant équipé ou de rues vides pendant le confinement', NOW(), NOW()),
(183, 89, 'image', 'https://www.who.int/images/default-source/wpro/coronavirus-2.jpg?sfvrsn=f3ceff40_19', 'Vidéo expliquant le virus SARS-CoV-2 et la pandémie de COVID-19', NOW(), NOW()),
(184, 90, 'image', 'https://www.cheminsdememoire.gouv.fr/sites/default/files/styles/fiche_visuel/public/2019-06/Signature%20de%20la%20Charte%20ONU%2026%20juin%2045_RV%2023245-1.jpg?itok=lLB3VPsH', 'Siège de l''ONU à New York ou du logo de l''ONU', NOW(), NOW()),
(185, 90, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant le rôle et le fonctionnement de l''ONU', NOW(), NOW()),
(186, 91, 'image', 'https://i.ytimg.com/vi/sV85Se4Kf1g/maxresdefault.jpg', 'Proclamation de l''indépendance de l''Inde ou d''une manifestation pour l''indépendance en Afrique', NOW(), NOW()),
(187, 91, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''histoire de la décolonisation en Asie et en Afrique', NOW(), NOW()),
(188, 92, 'image', 'https://www.bpi.fr/content/uploads/sites/4/2013/08/selma-to-montgomery-marches-resize640x428-1.jpg', 'Martin Luther King Jr. lors de la Marche sur Washington ou de Rosa Parks dans un bus', NOW(), NOW()),
(189, 92, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo documentaire sur le Mouvement des droits civiques', NOW(), NOW()),
(190, 93, 'image', 'https://www.demopolis.fr/wp-content/uploads/2021/06/Guerre-du-vietnam.jpeg', 'Image iconique de la Guerre du Vietnam (ex: "Napalm Girl" de Nick Ut)', NOW(), NOW()),
(191, 93, 'image', 'https://www.demopolis.fr/wp-content/uploads/2021/06/Guerre-du-vietnam.jpeg', 'Vidéo documentaire sur l''histoire de la Guerre du Vietnam', NOW(), NOW()),
(192, 94, 'image', 'https://asialyst.com/fr/wp-content/uploads/2021/01/chine-revolution-culturelle-gardes-rouges.jpg', 'Gardes rouges brandissant le Petit Livre rouge', NOW(), NOW()),
(193, 94, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les causes et les conséquences de la Révolution culturelle', NOW(), NOW()),
(194, 95, 'image', 'https://arenes.fr/wp-content/uploads/2022/06/urss_site.jpg', 'Mikhaïl Gorbatchev ou du drapeau soviétique abaissé au Kremlin', NOW(), NOW()),
(195, 95, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur les causes et les événements menant à la chute de l''URSS', NOW(), NOW()),
(196, 96, 'image', 'https://www.kezakoo.com/wp-content/uploads/2022/03/imageCarousel.imageformat.lightbox.png', 'Porte-conteneurs géant ou de logos de marques mondiales', NOW(), NOW()),
(197, 96, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les différentes facettes de la mondialisation contemporaine', NOW(), NOW()),
(198, 97, 'image', 'https://digital.essca.fr/wp-content/uploads/sites/5/2019/03/CBDA4BD4-8ADD-475F-8184-C1C3B76E3AB1.jpeg', 'Smartphones ou de réseaux de serveurs', NOW(), NOW()),
(199, 97, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo sur l''impact de la révolution numérique sur la société', NOW(), NOW()),
(200, 98, 'image', 'https://www.diasporadz.com/wp-content/uploads/2024/03/rechauffement-climatique-planete.jpg', 'Fonte des glaciers ou d''événements climatiques extrêmes', NOW(), NOW()),
(201, 98, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo expliquant les causes et les conséquences du changement climatique (Source: GIEC/IPCC)', NOW(), NOW()),
(202, 99, 'image', 'https://www.superprof.fr/ressources/wp-content/uploads/2006/07/nouveaux-mouvements-sociaux-scaled.jpg', 'Image d''une manifestation récente (ex: Marche pour le climat)', NOW(), NOW()),
(203, 99, 'video', 'https://www.nationalgeographic.fr/encyclopedie/data/images/1011264-La_guerre_de_Cent_Ans_1338-1350.jpg', 'Vidéo analysant les caractéristiques des mouvements sociaux contemporains', NOW(), NOW());